### ISSUE TITLE
 java.lang.RuntimeException: java.io.EOFException Android Jump v5.0

### ISSUE THREAD

**Issue by AgonLohaj** [janrain/jump.android#15]
This is the janrain config:
JumpConfig config = new JumpConfig();
        config.engageAppId = Constants.JANRAIN_ENGAGE_APP_ID;
        config.captureAppId = Constants.JANRAIN_CAPTURE_APP_ID;
        config.captureClientId = Constants.JANRAIN_CAPTURE_CLIENT_ID;
        config.captureDomain = Constants.JANRAIN_CAPTURE_DOMAIN;
        config.captureLocale = Locale.getDefault().equals(Locale.GERMANY) ? Constants.JANRAIN_CAPTURE_LOCALE_GERMAN : Constants.JANRAIN_CAPTURE_LOCALE_ENGLISH;
        config.captureFlowName = Constants.JANRAIN_CAPTURE_FLOW_NAME;
        config.captureEnableThinRegistration = false;
        config.traditionalSignInType = Jump.TraditionalSignInType.EMAIL; // or USERNAME
        config.captureSocialRegistrationFormName = Constants.JANRAIN_CAPTURE_SOCIAL_REGISTRATION_FORM_NAME;
        config.captureTraditionalSignInFormName = Constants.JANRAIN_CAPTURE_TRADITIONAL_SIGNIN_FORM_NAME;
        config.captureTraditionalRegistrationFormName = Constants.JANRAIN_CAPTURE_TRADITIONAL_REGISTRATION_FORM_NAME;
        config.captureForgotPasswordFormName = Constants.JANRAIN_CAPTURE_FORGOT_PASSWORD_FORM_NAME;
        Jump.init(this, config);

This is the error. When I clear the cache or reinstall the app it works.

E/AndroidRuntime﹕ FATAL EXCEPTION: JREngage-ThreadUtils~pool-3-thread-1
    java.lang.RuntimeException: java.io.EOFException
            at com.janrain.android.Jump.loadFlow(Jump.java:807)
            at com.janrain.android.Jump.access$100(Jump.java:85)
            at com.janrain.android.Jump$1.run(Jump.java:203)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.EOFException
            at java.io.DataInputStream.readByte(DataInputStream.java:77)
            at java.io.ObjectInputStream.nextTC(ObjectInputStream.java:505)
            at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:752)
            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
            at java.util.HashMap.readObject(HashMap.java:1003)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330)
            at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
            at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
            at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
            at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
            at com.janrain.android.Jump.loadFlow(Jump.java:800)
            at com.janrain.android.Jump.access$100(Jump.java:85)
            at com.janrain.android.Jump$1.run(Jump.java:203)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by Kevin-Janrain** [comment]
@AgonLohaj could you provide more detail on your setup/environment (such as Android version/s and device/s used) and a set of steps to reproduce the issue?  In the same environment does the simpledemo sample app work for you?

**Comment by AgonLohaj** [comment]
This happened running on 5.1 Nexus 5, also Galaxy S4 with Android 4.4. with the following app config:
android {
    compileSdkVersion 21
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.findmeoutside.guidefinder.android"
        minSdkVersion 9
        targetSdkVersion 20
        versionCode 101
        versionName "1.0.1"
        renderscriptSupportModeEnabled true
        multiDexEnabled false
    }
}
This issue doesn't happen always, just in some cases after using the app. So I cannot give you any steps to reproduce :/.

**Comment by Kevin-Janrain** [comment]
Ok, thanks for the additional information.

**Comment by pbjanrain** [comment]
Support issue. Closed due to inactivity.

**Comment by KonsoltCorp** [comment]
I have been seeing this issue a lot! The steps to reproduce in y case is simply to attempt sign in with no network available (for example Airplane mode).

**Comment by KonsoltCorp** [comment]
Also, this occurs if the refresh token request is sent after the device loses connection

**Comment by priyanRasp** [comment]
I facing this issue similar

E/AndroidRuntime: FATAL EXCEPTION: JREngage-ThreadUtils~pool-2-thread-1
                  Process: au.org.nps.medicinelistplus, PID: 1158
                  java.lang.RuntimeException: java.io.EOFException
                      at com.janrain.android.Jump.loadFlow(Jump.java:886)
                      at com.janrain.android.Jump.access$100(Jump.java:89)
                      at com.janrain.android.Jump$1.run(Jump.java:215)

**Comment by pbjanrain** [comment]
Perhaps you should open a support ticket with Janrain support and remember to include the full logs from your developer environment.  There isn't enough information here to provide any useful guidance.  My first suspicion would be that you are running into some form of issue in this method:  at com.janrain.android.Jump.loadFlow(Jump.java:886)

https://github.com/janrain/jump.android/blob/master/Jump/src/main/java/com/janrain/android/Jump.java#L865-L892

It is trying to read the flow configuration from the devices local storage.  There may be some form of issue with how you are storing the information or how you have initialized the library that is preventing the data from being stored or read properly.
