### ISSUE TITLE
app crashes: cause>> java.io.EOFException

### ISSUE THREAD

**Issue by priyanRasp** [janrain/jump.android#19]
Hi I am using JUMP for capture integration.

I followed following steps to integrate capture.

Jump initialization: 
public class NpsApp extends Application {
.....
 @Override
    public void onCreate() {
        super.onCreate();
sInstance = NpsApp.this;

        JumpConfig jumpConfig = new JumpConfig();
        jumpConfig.engageAppId = "xxxxxxxxxxxxxxxxxxxxxxx";
        jumpConfig.captureDomain = "xxxxxxxxxxxxxxxxxxx";
        jumpConfig.captureClientId = "xxxxxxxxxxxxxxxxxxxxx";
        jumpConfig.captureLocale = "en-US";
        jumpConfig.captureTraditionalSignInFormName = "userInformationForm";
        jumpConfig.traditionalSignInType = Jump.TraditionalSignInType.EMAIL;
        jumpConfig.captureAppId = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        jumpConfig.captureFlowName = "standard";
        jumpConfig.captureFlowVersion = "HEAD";
        jumpConfig.captureSocialRegistrationFormName = "socialRegistrationForm";
        jumpConfig.captureTraditionalRegistrationFormName = "registrationForm";
        jumpConfig.captureEditUserProfileFormName = "editProfileForm";
        jumpConfig.captureEnableThinRegistration = false;
        jumpConfig.captureForgotPasswordFormName = "forgotPasswordForm";
        jumpConfig.captureResendEmailVerificationFormName = "resendVerificationForm";
        Jump.init(this, jumpConfig);
}
}

on each activity I used to call Jump.saveToDisk(this); inside onPause() method.

I can download flow, able login successfully and account is created in capture record also successfully. App works fine. 

But some time, If try to launch application, then app crashes. Please check the log

E/AndroidRuntime: FATAL EXCEPTION: JREngage-ThreadUtils~pool-2-thread-1
                  Process: au.org.nps.medicinelistplus, PID: 9935
                  java.lang.RuntimeException: java.io.EOFException
                      at com.janrain.android.Jump.loadFlow(Jump.java:886)
                      at com.janrain.android.Jump.access$100(Jump.java:89)
                      at com.janrain.android.Jump$1.run(Jump.java:215)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.io.EOFException
                      at java.io.DataInputStream.readByte(DataInputStream.java:77)
                      at java.io.ObjectInputStream.nextTC(ObjectInputStream.java:505)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:752)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at java.util.HashMap.readObject(HashMap.java:1003)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330)
                      at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at java.util.HashMap.readObject(HashMap.java:1004)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330)
                      at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at java.util.HashMap.readObject(HashMap.java:1004)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330)
                      at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at com.janrain.android.Jump.loadFlow(Jump.java:879)
                      at com.janrain.android.Jump.access$100(Jump.java:89) 
                      at com.janrain.android.Jump$1.run(Jump.java:215) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:818) 
E/WindowManager: android.view.WindowLeaked: Activity au.org.nps.medicinelistplus.ui.activity.SplashActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{305291da V.E..... R....... 0,0-684,375} that was originally added here
                     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:375)
                     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                     at android.app.Dialog.show(Dialog.java:298)
                     at net.hockeyapp.android.CrashManager.showDialog(CrashManager.java:549)
                     at net.hockeyapp.android.CrashManager.execute(CrashManager.java:185)
                     at net.hockeyapp.android.CrashManager.register(CrashManager.java:125)
                     at net.hockeyapp.android.CrashManager.register(CrashManager.java:97)
                     at net.hockeyapp.android.CrashManager.register(CrashManager.java:85)
                     at au.org.nps.medicinelistplus.ui.activity.SplashActivity.checkForCrashes(SplashActivity.java:98)
                     at au.org.nps.medicinelistplus.ui.activity.SplashActivity.onResume(SplashActivity.java:66)
                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1280)
                     at android.app.Activity.performResume(Activity.java:6096)
                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3011)
                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3063)
                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
                     at android.app.ActivityThread.access$800(ActivityThread.java:155)
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:135)
                     at android.app.ActivityThread.main(ActivityThread.java:5343)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at java.lang.reflect.Method.invoke(Method.java:372)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

Once app crashes I am not able launch application again, It keep on crashing. But even app crashes I have some background job, It is still working.

**Comment by pbjanrain** [comment]
Where in the world (geographically) are you physically located?  I have seen issues where developers are very far away from the actual Capture application and they run into timeouts trying to load the flow files due to poor network performance.  You should geo-locate the Capture instance that you are testing against and perhaps test the speed between your phone and the Capture instance.  You may have to increase the network timeouts.

**Comment by pbjanrain** [comment]
Closing issue due to lack of response.
