### ISSUE TITLE
App is getting crash when it is tried Jump.saveToDisk(this);

### ISSUE THREAD

**Issue by priyanRasp** [janrain/jump.android#32]
Please check below error log. User is not able to use the application once app got crashed.

E/AndroidRuntime: FATAL EXCEPTION: JREngage-ThreadUtils~pool-2-thread-1*
                  Process: au.org.nps.medicinelistplus, PID: 3765
                  java.lang.IndexOutOfBoundsException: Invalid index 115, size is 80
                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                      at java.util.ArrayList.get(ArrayList.java:308)
                      at java.io.ObjectInputStream.registeredObjectRead(ObjectInputStream.java:2123)
                      at java.io.ObjectInputStream.readCyclicReference(ObjectInputStream.java:807)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:773)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at java.io.ObjectInputStream.readFieldValues(ObjectInputStream.java:1113)
                      at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:454)
                      at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1345)
                      at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at java.util.HashMap.readObject(HashMap.java:1004)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330)
                      at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
                      at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
                      at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                      at com.janrain.android.utils.Archiver.load(Archiver.java:160)
                      at com.janrain.android.utils.Archiver.load(Archiver.java:136)
                      at com.janrain.android.engage.session.JRSession.initialize(JRSession.java:283)
                      at com.janrain.android.engage.session.JRSession.<init>(JRSession.java:226)
                      at com.janrain.android.engage.session.JRSession.getInstance(JRSession.java:161)
                      at com.janrain.android.engage.JREngage$1.run(JREngage.java:271)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)

**Comment by pbjanrain** [comment]
Unfortunately, without the full implementation of your code and the integration with the libraries there is not enough information to provide any advice.

You may want to set a break point around this location and see what the variables and context are during the IO operation.

https://github.com/janrain/jump.android/blob/master/Jump/src/main/java/com/janrain/android/capture/CaptureRecord.java#L150-L176

It is possible that the user's "state" was not saved properly.  Please refer to the documentation on persisting the user object:

https://github.com/janrain/jump.android/blob/master/Docs/Jump_Integration_Guide.md#call-the-load-and-store-hooks

Please use the Janrain Support portal for technical support inquiries if you require additional support.
