### ISSUE TITLE
7.0.4 leaking service connection

### ISSUE THREAD

**Issue by andressantiago** [janrain/jump.android#38]
So the social sign in works fine now. However, seems that the `AuthorizationService` seems to be leaked when returning to the activity where the `AuthorizationService` was set.

```
AuthorizationService authorizationService = new AuthorizationService(this); mEngage.setAuthorizationService(authorizationService);
mEngage.setAuthorizationActivity(this);
mEngage.showAuthenticationDialog(this, "googleplus");
```

Stack Trace

```
Activity [OUR PACKAGE].SignInActivity has leaked ServiceConnection net.openid.appauth.CustomTabManager$1@88b7c83 that was originally bound here

android.app.ServiceConnectionLeaked: Activity [OUR PACKAGE].SignInActivity has leaked ServiceConnection net.openid.appauth.CustomTabManager$1@88b7c83 
    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)

    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)

    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)

    at android.app.ContextImpl.bindService(ContextImpl.java:1422)

    at android.content.ContextWrapper.bindService(ContextWrapper.java:636)

    at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:68)

    at net.openid.appauth.CustomTabManager.bind(CustomTabManager.java:85)

    at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:107)

    at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:85)

    at net.openid.appauth.AuthorizationService.<init>(AuthorizationService.java:74)

    at [OUR PACKAGE].SignInActivity.onGooglePlusClick(SignInActivity.java:337)

    at [OUR PACKAGE].fragments.SocialSignInFragment.onClick(SocialSignInFragment.java:163)

    at android.view.View.performClick(View.java:5637)

    at android.view.View$PerformClick.run(View.java:22429)

    at android.os.Handler.handleCallback(Handler.java:751)

    at android.os.Handler.dispatchMessage(Handler.java:95)

    at android.os.Looper.loop(Looper.java:154)

    at android.app.ActivityThread.main(ActivityThread.java:6119)

    at java.lang.reflect.Method.invoke(Native Method)

    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)

    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by pbjanrain** [comment]
That is most likely happening because your "SignInActivity" is not the same activity that is being set in those additional calls:
`
AuthorizationService authorizationService = new AuthorizationService( [OUR PACKAGE].SignInActivity); 
mEngage.setAuthorizationService(authorizationService);
mEngage.setAuthorizationActivity( [OUR PACKAGE].SignInActivity);
`
You may have to change the fromActivity for `mEngage.showAuthenticationDialog(this, "googleplus");` but it depends on how your app is built.

Essentially, you need to bind the AuthorizationService to the activity that will be handling the response from the OpenID AppAuth calls that are handled by the browser.

**Comment by andressantiago** [comment]
the same SignInActivity that is calling the `showAuthenticationDialog` is also handling the callbacks `jrAuthenticationDidSucceedForUser`, and `jrAuthenticationDidNotComplete`.

**Comment by pbjanrain** [comment]
It's kind of confusing.  Since we are now using the OpenID AppAuth libraries for doing the Google authentication there is some special handling that needs to be done.  The AuthorizationService needs to bind to the activity that will be receiving the oauth call backs from the system browser.

```
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:scheme="https"
                android:host="com.googleusercontent.apps.UPDATE_WITH_GOOGLE_CLIENT_ID:"
                android:path="/oauth2redirect"/>
        </intent-filter>
    </activity>
```
This activity may not be the same activity that you are usiing for the `jrAuthentication...` callbacks AND it may be different than the Activity that is initiating the `mEngage.showAuthenticationDialog` method.  

The purpose of the mEngage.setAuthorizationActivity is to make sure we refer to the correct activity when initiating the AppAuth libraries.  If you try to bind to say a FragmentActivity it is disposed when no longer used and the ServiceConnectionLeaked error occurs.  Essentially, the `net.openid.appauth.RedirectUriReceiverActivity`  correlates to the URL that the system browser will use to redirect back to the app when it completes any oauth2 redirect process.  This is related to your Google oAuth client class path when you set up the Google oAuth Android client in the Google Developer console.

Hopefully, this clarifies and doesn't confuse.

**Comment by andressantiago** [comment]
Seems to be an issue with a dependency you have on OpenID.

https://github.com/openid/AppAuth-Android/issues/134

**Comment by pbjanrain** [comment]
Yes - but it can be worked around by following the steps above.  This is how we do it in the Capture implementation.

**Comment by rahulsingh0089** [comment]
In the above example, what is mEngage . I am confused in this.

**Comment by pbjanrain** [comment]
Try referring to this file and code:
https://github.com/janrain/jump.android/blob/master/Jump/src/main/java/com/janrain/android/Jump.java#L457-L459
